FROM node:18-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN cp node_modules/pdfjs-dist/build/pdf.worker.min.mjs public/pdf.worker.min.mjs
EXPOSE 3000
ENV WATCHPACK_POLLING=true
CMD ["npm", "start"]
